### PR TITLE
Adds support for uploading files to a Slack channel

### PR DESCRIPTION
**Pull request by metalbot**
Modifies the ISlackConnection and IChatClient interfaces to support uploading a file to slack, using mechanisms very similar to the existing Say and PostMessage implementations.

Also allows you to set the channel for integration testing (was hard coded to #general).

### CODE REVIEW

**Comment by Workshop2** [comment]
Hello @metalbot - I haven't forgotten your pull request.

I want to extend this to use streams instead of using the file system before accepting it 😄

**Comment by AlexJH4U** [comment]
Does this project website have a forum  where I can post a comment/question.  Looks like the only way is to create a PR.   I'm getting crashes when a user e-mails the "bot" for the first time.  It's a key not found in dictionary exception, created in the HandleMessage(inboundMessage) method of SlackConnection.  Even though the inboundMessage has a Channel string provided, t is not present in the _connectedHubs dictionary.  Perhaps it just needs to sleep for a while to let the _connectedHubs dictionary to update?  
Apologies for the placement of the comment.

**Comment by Workshop2** [comment]
@AlexJH4U you should raise an issue - pull requests are for code changes.

**Comment by Workshop2** [comment]
Also @metalbot - if you are able to make a new client for uploading instead of using the chat client that would be great 👍

**Comment by Workshop2** [comment]
Yes, I believe it should fix it

**Pull request closed without merging**
